import datetime
def editable_function():
        print("I added a line.")
        print("I added a line.")
        print("I added a line.")
        print("I added a line.")
        print("I added a line.")
        print("I added a line.")
        print("I added a line.")
        print("I added a line.")
        print("I added a line.")
        print("I added a line.")
        print("I added a line.")
        print("I added a line.")
        print("I added a line.")
        print("I added a line.")
        print("I added a line.")
        print("I added a line.")
        print("I added a line.")
        print("I added a line.")
        print("I added a line.")
        print("I added a line.")
        print("I loaded:"+str(datetime.datetime.utcnow()))
